---
title: "Crypto_Analysis"
output: html_notebook
Author: Köffel Fabian, Amann Matthias
---
```{r load package crypto2}
devtools::install_github("jessevent/crypto", force= TRUE)
pacman::p_load(gganimate,gifski,png,gapminder)
pacman::p_load(tidyverse,tidyquant,FFdownload,tsibble, tibbletime, rstudioapi, data.table, crypto2)
options("scipen"=100, "digits"=4)
```

```{r All aktive coins from 2014 - 6th October 2020}
coin_list <- crypto_list(start_date_hist = "20140101", end_date_hist = "20201006", date_gap = "months")
```

So, the total number of crypto currencies is __1579__. 

```{r Getting the historic data of crypto currencies}
#be aware that without a limiting factor it could be a very long lasting download
coin_hist <- na.omit(crypto_history(coin_list, limit=95, start_date="20140101", end_date = "20201006", sleep = 1))
coin_hist
```

```{r All active coins over several subperiods}
#prepared coin history
prep_coin_hist <- coin_hist %>%
  select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
  filter(between(date, as.Date("2013-01-01"), as.Date("2020-10-06"))) %>%
  group_by(symbol)

#2013
coin_hist_2013 <- coin_hist %>%
  select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
  filter(between(date, as.Date("2013-01-01"), as.Date("2013-12-31"))) %>%
  group_by(symbol) # For some reason it downloads the variables, but without any observation

#2014
coin_hist_2014 <- coin_hist %>%
  select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
  filter(between(date, as.Date("2014-01-01"), as.Date("2014-12-31"))) %>%
  group_by(symbol)

#2015
coin_hist_2015 <- coin_hist %>%
     select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
     filter(between(date, as.Date("2015-01-01"), as.Date("2015-12-31"))) %>%
  group_by(symbol)

#2016
coin_hist_2016 <- coin_hist %>%
     select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
     filter(between(date, as.Date("2016-01-01"), as.Date("2016-12-31"))) %>%
  group_by(symbol)

#2017
coin_hist_2017 <- coin_hist %>%
     select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
     filter(between(date, as.Date("2017-01-01"), as.Date("2017-12-31"))) %>%
  group_by(symbol)

#2018
coin_hist_2018 <- coin_hist %>%
     select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
     filter(between(date, as.Date("2018-01-01"), as.Date("2018-12-31"))) %>%
  group_by(symbol)

#2019
coin_hist_2019 <- coin_hist %>%
     select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
     filter(between(date, as.Date("2019-01-01"), as.Date("2019-12-31"))) %>%
  group_by(symbol)

#2020 until 6th October
coin_hist_2020 <- coin_hist %>%
     select(date, symbol, name, open, close, high, low, volume, market, close_ratio, spread) %>%
     filter(between(date, as.Date("2020-01-01"), as.Date("2020-10-06"))) %>%
  group_by(symbol)
```

```{r Risk / Return calculation}
return_all <- stats::aggregate(x = prep_coin_hist[,3:4], list(prep_coin_hist$name), mean)
risk_all <- stats::aggregate(x = prep_coin_hist[,3:4], list(prep_coin_hist$name),sd)
return_all$name <- NULL
risk_all$name <- NULL
return_risk_all <- dplyr::left_join(x = return_all, y= risk_all, by= "Group.1")
names(return_risk_all)[names(return_risk_all)=="open.x"] <- "Mu"
names(return_risk_all)[names(return_risk_all)=="open.y"] <- "Sigma"
names(return_risk_all)[names(return_risk_all)=="Group.1"] <- "Name"
return_risk_all
```


```{r Calculating the returns and risk for 2019}
return <- stats::aggregate(x = coin_hist_2019[,3:4], list(coin_hist_2019$name), mean)
risk <- stats::aggregate(x = coin_hist_2019[,3:4], list(coin_hist_2019$name),sd)
return$name <- NULL
risk$name <- NULL
return_risk <- dplyr::left_join(x = return, y= risk, by= "Group.1")
names(return_risk)[names(return_risk)=="open.x"] <- "Mu"
names(return_risk)[names(return_risk)=="open.y"] <- "Sigma"
names(return_risk)[names(return_risk)=="Group.1"] <- "Name"
return_risk
```
```{r Calculation of 2018}
return_nd <- stats::aggregate(x = coin_hist_2018[,3:4], list(coin_hist_2018$name), mean)
risk_nd <- stats::aggregate(x = coin_hist_2018[,3:4], list(coin_hist_2018$name),sd)
return_nd$name <- NULL
risk_nd$name <- NULL
return_risk_nd <- dplyr::left_join(x = return_nd, y= risk_nd, by= "Group.1")
names(return_risk_nd)[names(return_risk_nd)=="open.x"] <- "Mu"
names(return_risk_nd)[names(return_risk_nd)=="open.y"] <- "Sigma"
names(return_risk_nd)[names(return_risk_nd)=="Group.1"] <- "Name"
return_risk_nd
```


```{r Plotting the small sample to get a feeling for the data}
ggplot(return_risk,aes(x=Sigma, y=Mu,label=Name)) + geom_point(alpha =0.6) + scale_x_log10() + scale_y_log10() + geom_text(aes(label=Name),hjust=0, vjust=0) + ggtitle("2019")
ggplot(return_risk_nd,aes(x=Sigma, y=Mu,label=Name)) + geom_point(alpha =0.6) + scale_x_log10() + scale_y_log10() + geom_text(aes(label=Name),hjust=0, vjust=0) + ggtitle("2018")
ggplot(return_risk_all, aes(x=Sigma, y=Mu, label = Name)) + geom_point(alpha = 0.6) + scale_x_log10() + scale_y_log10() + geom_text(aes(label = Name), hjust=0, vjust=0) + ggtitle("All")
```
```{r Looking for cluters, so therefore we leave the lables out}
ggplot(return_risk,aes(x=Sigma, y=Mu)) + geom_point(alpha =0.6) + scale_x_log10() + scale_y_log10()  + ggtitle("2019")
ggplot(return_risk_nd,aes(x=Sigma, y=Mu)) + geom_point(alpha =0.6) + scale_x_log10() + scale_y_log10() + ggtitle("2018")
ggplot(return_risk_all, aes(x=Sigma, y=Mu)) + geom_point(alpha = 0.6) + scale_x_log10() + scale_y_log10() + ggtitle("All")
```






